"""updated role table

Revision ID: 4d66786068a2
Revises: a80b3f5cd631
Create Date: 2017-02-23 16:20:44.202702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d66786068a2'
down_revision = 'a80b3f5cd631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permissions')
    op.drop_column('role', 'default')
    # ### end Alembic commands ###
